<a href="https://colab.research.google.com/github/leemutai/13th/blob/main/sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
x = 34-23
y = "Hello"
z= 3.45
if z == 3.45 or y =="Hello":
    x = x+1
    y = y + "World"
print(x)
print(y)

12
HelloWorld


In [11]:
#python opertations
x= 3
print(x)
print(x+1)
print(x-1)
print(x*2)
print(x**2)
x+=1
print(x)
x *= 2
print(x)
y=2.5
print(y,y+1,y+2,y**2)

3
4
2
6
9
4
8
2.5 3.5 4.5 6.25


In [12]:
#functions in python
def sign(x):
  if x>0:
    return 'positive'
  elif x<0:
    return 'negative'
  else:
    return 'zero'
  for x in [-1,0,1]:
    print(sign(x))

In [17]:
import numpy as np

scores = [89, 56, 34, 76, 89, 98]
first_arr = np.array(scores)
print(first_arr)

S = np.sum(first_arr)
print(S)

mn = np.min(first_arr)
mx = np.max(first_arr)
print(mn)
print(mx)

e = np.random.random((2, 2))  # create an array filled with random values
print(e)

datamean =np.mean(first_arr)
print(datamean)
datasum=np.sum(first_arr)
print(datasum)


[89 56 34 76 89 98]
442
34
98
[[0.28696364 0.31456989]
 [0.47154718 0.96334976]]
73.66666666666667
442


In [18]:
import numpy as np  # Import the NumPy library and alias it as np

dt = np.random.randint(5, 15, 20)  # Generate an array of 20 random integers between 5 and 14 inclusive
print(dt)  # Print the generated array

np.mean(dt)  # Calculate the mean of the array (this line doesn't print or store the mean)

np.median(dt)  # Calculate the median of the array (this line doesn't print or store the median)

from statistics import mode  # Import the mode function from the statistics module

mode(dt)  # Calculate the mode of the array and return the most common value


[ 6 11  8 11  8 12  5 12 14  7  8 13  8 14  9  5 12 10  7 14]


8

In [23]:
import numpy as np  # Import the NumPy library and alias it as np

a = np.array([1, 2, 3])  # Create a 1-dimensional NumPy array with elements 1, 2, and 3
print(a)  # Print the array

a = np.array([[1, 2], [3, 4]])  # Create a 2-dimensional NumPy array with elements arranged in a 2x2 matrix
print(a)  # Print the array

# This line raises a syntax error as the array constructor is incorrectly used
# The correct way to create a 2-dimensional array is to enclose each row in a list
# Here, we'll fix it by surrounding both lists with square brackets
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)  # Print the corrected array

# This line raises a TypeError as the shape attribute is assigned with a float (3.2)
# The shape attribute should be assigned with a tuple containing the desired dimensions
# Let's fix it by assigning the shape attribute with a tuple (3, 2)
a.shape = (3, 2)
print(a)  # Print the reshaped array


[1 2 3]
[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#array maths
x = np.array([])